/**
 * Created by zhouzhengh on 2018/11/17.
 */
export const GETDATA_LIST = 'GETDATA_LIST'
export const REFRESH_AJAX = 'REFRESH_AJAX'
export const GETNEWS_CONTENT = 'GETNEWS_CONTENT'
export const GETNEWS_VIDEO = 'GETNEWS_VIDEO'
export const GETCOMMENT_DATA = 'GETCOMMENT_DATA'
export const GETSEARCH_DATA = 'GETSEARCH_DATA'
export const GETHOT_DATA = 'GETHOT_DATA'
export const GETROUTER_NAME = 'GETROUTER_NAME'
export const SOCIETY_DATA = 'SOCIETY_DATA'
export const ENTERTAINMENT_DATA = 'ENTERTAINMENT_DATA'
export const GETMILITARY_DATA = 'GETMILITARY_DATA'
export const GETSPORT_DATA = 'GETSPORT_DATA'
export const GETWORLD_DATA = 'GETWORLD_DATA'
export const GETFASHION_DATA = 'GETFASHION_DATA'
export const GETCONTENT_NAME = 'GETCONTENT_NAME'
